/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT3_14 (number 28), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT0_PCR16_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT0_PCR17_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR28_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT0_17 (number 44), DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOLEDIOPINS_DC_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITOLEDIOPINS_DC_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITOLEDIOPINS_DC_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITOLEDIOPINS_DC_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITOLEDIOPINS_DC_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITOLEDIOPINS_DC_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITOLEDIOPINS_DC_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT2_28 (number 22), RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOLEDIOPINS_RST_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITOLEDIOPINS_RST_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITOLEDIOPINS_RST_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define BOARD_INITOLEDIOPINS_RST_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITOLEDIOPINS_RST_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITOLEDIOPINS_RST_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITOLEDIOPINS_RST_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_16 (number 43), CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOLEDIOPINS_CS_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITOLEDIOPINS_CS_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITOLEDIOPINS_CS_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITOLEDIOPINS_CS_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITOLEDIOPINS_CS_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITOLEDIOPINS_CS_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITOLEDIOPINS_CS_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOLEDIOPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
